INSERT INTO categories (category_name) VALUES ('Electronics');
INSERT INTO categories (category_name) VALUES ('Computers & Accessories');
INSERT INTO categories (category_name) VALUES ('Smartphones & Tablets');
INSERT INTO categories (category_name) VALUES ('Clothing & Apparel');
INSERT INTO categories (category_name) VALUES ('Footwear');
INSERT INTO categories (category_name) VALUES ('Home & Kitchen');
INSERT INTO categories (category_name) VALUES ('Furniture');
INSERT INTO categories (category_name) VALUES('Books & Stationery');
INSERT INTO categories (category_name) VALUES ('Beauty & Personal Care');
INSERT INTO categories (category_name) VALUES ('Health & Wellness');
INSERT INTO categories (category_name) VALUES ('Sports & Outdoors');
INSERT INTO categories (category_name) VALUES ('Toys & Games');
INSERT INTO categories (category_name) VALUES ('Garden & Outdoor Living');
INSERT INTO categories (category_name) VALUES ('Automotive');
INSERT INTO categories (category_name) VALUES ('Grocery & Staples');
INSERT INTO categories (category_name) VALUES ('Jewelry & Watches');
INSERT INTO categories (category_name) VALUES ('Music & Instruments');
INSERT INTO categories (category_name) VALUES ('Movies & TV Shows');
INSERT INTO categories (category_name) VALUES ('Baby Products');
INSERT INTO categories (category_name) VALUES ('Pet Supplies');
INSERT INTO categories (category_name) VALUES ('Office Products');
INSERT INTO categories (category_name) VALUES ('Tools & Home Improvement');
INSERT INTO categories (category_name) VALUES ('Arts & Crafts');
INSERT INTO categories (category_name) VALUES ('Travel & Luggage');
INSERT INTO categories (category_name) VALUES ('Fitness & Exercise');
INSERT INTO categories (category_name) VALUES ('Catering & Food Services');
INSERT INTO categories (category_name) VALUES ('Grocery & Gourmet Food');
INSERT INTO categories (category_name) VALUES ('Smart Home & Security');
INSERT INTO categories (category_name) VALUES ('Electric Vehicles & Accessories');
INSERT INTO categories (category_name) VALUES ('Wearable Technology');
INSERT INTO categories (category_name) VALUES ('Wedding & Bridal');
INSERT INTO categories (category_name) VALUES ('Vintage & Collectibles');
INSERT INTO categories (category_name) VALUES ('Industrial & Scientific');
INSERT INTO categories (category_name) VALUES ('Software & Digital Tools');
INSERT INTO categories (category_name) VALUES ('Religious & Spiritual Items');
INSERT INTO categories (category_name) VALUES ('Gifts & Special Occasion');
INSERT INTO categories (category_name) VALUES ('Party Supplies & Decorations');
INSERT INTO categories (category_name) VALUES ('Camping & Hiking Gear');
INSERT INTO categories (category_name) VALUES ('Sailing & Water Sports');
INSERT INTO categories (category_name) VALUES ('Bicycles & Accessories');
INSERT INTO categories (category_name) VALUES ('Cycling Equipment');
INSERT INTO categories (category_name) VALUES ('Hair Care & Styling');
INSERT INTO categories (category_name) VALUES ('Makeup & Cosmetics');
INSERT INTO categories (category_name) VALUES ('Skincare & Treatments');
INSERT INTO categories (category_name) VALUES ('Men''s Fashion');
INSERT INTO categories (category_name) VALUES ('Women''s Fashion');
INSERT INTO categories (category_name) VALUES ('Plus Size Clothing');
INSERT INTO categories (category_name) VALUES ('Maternity Wear');
INSERT INTO categories (category_name) VALUES ('Children''s Clothing');
INSERT INTO categories (category_name) VALUES ('Shoes & Sneakers');
INSERT INTO categories (category_name) VALUES ('Handbags & Wallets');
INSERT INTO categories (category_name) VALUES ('Sunglasses & Eyewear');
INSERT INTO categories (category_name) VALUES ('Surround Sound & Audio');
INSERT INTO categories (category_name) VALUES ('Cameras & Photography');
INSERT INTO categories (category_name) VALUES ('Video Game Consoles');
INSERT INTO categories (category_name) VALUES ('PC Gaming Accessories');
INSERT INTO categories (category_name) VALUES ('Networking & Smart Devices');
INSERT INTO categories (category_name) VALUES ('Printers & Scanners');
INSERT INTO categories (category_name) VALUES ('Wireless & Bluetooth Speakers');
